export const DOCUMENT_STATUSES = ["uploaded", "queued", "processing", "needs_review", "needs_correction", "reviewed", "approved", "rejected", "replaced", "failed", "archived"] as const;
export type DocumentStatus = typeof DOCUMENT_STATUSES[number];
export type DocumentAction = "review" | "approve" | "reject" | "archive" | "correct";

const legacy: Record<string, DocumentStatus> = { recibido: "uploaded", procesando: "processing", procesado: "needs_review", "requiere atención": "needs_review", "requiere revision": "needs_review", "requiere revisión": "needs_review", aprobado: "approved", rechazado: "rejected", error: "failed" };
export const statusMeta: Record<DocumentStatus, { label: string; className: string }> = {
  uploaded: { label: "Cargado", className: "bg-slate-100 text-slate-700" }, queued: { label: "En cola", className: "bg-slate-100 text-slate-700" }, processing: { label: "Procesando", className: "bg-blue-100 text-blue-800" }, needs_review: { label: "Requiere revisión", className: "bg-amber-100 text-amber-800" }, needs_correction: { label: "Requiere corrección", className: "bg-orange-100 text-orange-800" }, reviewed: { label: "Revisado", className: "bg-cyan-100 text-cyan-800" }, approved: { label: "Aprobado", className: "bg-emerald-100 text-emerald-800" }, rejected: { label: "Rechazado", className: "bg-red-100 text-red-800" }, replaced: { label: "Reemplazado", className: "bg-slate-200 text-slate-700" }, failed: { label: "Error técnico", className: "bg-red-200 text-red-950" }, archived: { label: "Archivado", className: "bg-slate-200 text-slate-600" },
};
export function normalizeDocumentStatus(value?: string | null): DocumentStatus { const normalized = String(value || "").trim().toLowerCase(); return (DOCUMENT_STATUSES as readonly string[]).includes(normalized) ? normalized as DocumentStatus : legacy[normalized] || "uploaded"; }
const transitions: Record<DocumentStatus, DocumentStatus[]> = { uploaded: ["queued", "processing", "replaced"], queued: ["processing", "failed"], processing: ["needs_review", "needs_correction", "failed"], needs_review: ["reviewed", "needs_correction", "rejected"], needs_correction: ["uploaded", "rejected"], reviewed: ["approved", "rejected", "needs_correction"], approved: ["archived"], rejected: [], replaced: [], failed: ["uploaded", "queued"], archived: [] };
export function canTransition(from: string | null | undefined, to: DocumentStatus) { return transitions[normalizeDocumentStatus(from)].includes(to); }
const permissions: Record<DocumentAction, string[]> = { review: ["firm_admin", "supervisor", "accountant", "assistant"], approve: ["firm_admin", "supervisor", "accountant"], reject: ["firm_admin", "supervisor", "accountant"], archive: ["firm_admin"], correct: ["firm_admin", "supervisor", "accountant", "assistant"] };
export function canPerformDocumentAction(role: string, action: DocumentAction) { return permissions[action].includes(role); }
