"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, FileText, FolderOpen, Search, UploadCloud } from "lucide-react";
import { PortalShell } from "./portal-shell";
import { DocumentUploader } from "./document-uploader";
import { PortalDocument, statusLabel, useDocumentSummary, usePortalDocuments } from "./portal-data";

function Empty({title,body}:{title:string;body:string}){return <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><FolderOpen className="mx-auto text-slate-400" size={30}/><h2 className="mt-3 font-bold text-slate-800">{title}</h2><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">{body}</p></div>}
function Badge({status}:{status:string}){const s=status.toLowerCase();const c=s.includes("aprob")?"bg-emerald-100 text-emerald-800":s.includes("atenci")||s.includes("revisi")?"bg-amber-100 text-amber-800":s.includes("error")?"bg-red-100 text-red-800":s.includes("proces")?"bg-blue-100 text-blue-800":"bg-slate-100 text-slate-700";return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${c}`}>{statusLabel(status)}</span>}
function DocumentList({documents}:{documents:PortalDocument[]}){const [search,setSearch]=useState("");const rows=useMemo(()=>documents.filter(d=>`${d.nombre_archivo} ${d.tipo_documento} ${d.rfc_detectado}`.toLowerCase().includes(search.toLowerCase())),[documents,search]);return <><div className="mb-4 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} className="bro-input !mt-0 pl-10" placeholder="Buscar documento, RFC o categoría"/></label></div>{rows.length===0?<Empty title="Sin documentos que coincidan" body="Ajusta la búsqueda o carga un documento para iniciar el expediente."/>:<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden grid-cols-[1.8fr_1fr_1fr_1fr] gap-4 border-b bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-slate-500 md:grid"><span>Documento</span><span>Fecha</span><span>Total</span><span>Estado</span></div>{rows.map(doc=><Link href={`/expediente/${doc.id}`} key={doc.id} className="grid gap-2 border-b border-slate-100 px-5 py-4 transition hover:bg-orange-50 md:grid-cols-[1.8fr_1fr_1fr_1fr]"><div><p className="font-bold text-slate-800">{doc.nombre_archivo||doc.tipo_documento}</p><p className="mt-1 text-xs text-slate-500">{doc.tipo_documento}</p></div><span className="text-sm text-slate-600">{doc.fecha_documento||new Date(doc.created_at).toLocaleDateString("es-MX")}</span><span className="text-sm font-semibold text-slate-700">{doc.total==null?"Sin importe":`$${Number(doc.total).toLocaleString("es-MX")}`}</span><div><Badge status={doc.estatus}/></div></Link>)}</div>}</>}

export function HomePage(){const {documents,loading,error}=usePortalDocuments();const summary=useDocumentSummary(documents);const cards=[["Recibidos",summary.received,FileText,"/expediente"],["Procesando",summary.processing,Clock3,"/expediente"],["Requieren revisión",summary.attention,AlertTriangle,"/expediente"],["Aprobados",summary.approved,CheckCircle2,"/expediente"]] as const;return <PortalShell title="Inicio" description="Resumen operativo de la documentación disponible."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon,href])=><Link href={href} key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-orange-300"><Icon size={19} className="text-[#ff6a00]"/><p className="mt-4 text-3xl font-extrabold">{loading?"—":value}</p><p className="mt-1 text-sm font-semibold text-slate-600">{label}</p></Link>)}</div>{error?<div className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>:documents.length===0&&!loading?<div className="mt-6"><Empty title="Tu expediente aún no tiene documentos" body="Carga el primer PDF, XML o imagen para comenzar el proceso documental."/><Link href="/enviar-documentos" className="mx-auto mt-4 flex w-fit items-center gap-2 rounded-xl bg-[#ff6a00] px-4 py-3 text-sm font-bold text-white"><UploadCloud size={17}/> Enviar documentos</Link></div>:<section className="mt-7 grid gap-5 lg:grid-cols-3"><div className="lg:col-span-2"><h2 className="mb-3 text-lg font-bold">Actividad reciente</h2><DocumentList documents={documents.slice(0,5)}/></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Acciones disponibles</h2><Link href="/enviar-documentos" className="mt-4 flex items-center justify-between rounded-xl bg-[#ff6a00] px-4 py-3 text-sm font-bold text-white">Enviar documentos <ArrowRight size={16}/></Link><Link href="/expediente" className="mt-3 flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Ver expediente <ArrowRight size={16}/></Link></div></section>}</PortalShell>}
export function UploadPage(){const {refresh}=usePortalDocuments();return <PortalShell title="Enviar documentos" description="Los archivos permitidos se validan localmente antes de enviarse al almacenamiento privado."><DocumentUploader onComplete={refresh}/></PortalShell>}
export function ExpedientePage(){const {documents,loading,error}=usePortalDocuments();return <PortalShell title="Expediente" description="Consulta los documentos disponibles y abre su detalle.">{error?<Empty title="No fue posible consultar el expediente" body={error}/>:loading?<Empty title="Cargando expediente" body="Estamos consultando los documentos disponibles."/>:<DocumentList documents={documents}/>}</PortalShell>}
export function EmptyModule({module}:{module:"Aclaraciones"|"Reportes"|"Perfil y configuración"}){const {documents,loading}=usePortalDocuments();const summary=useDocumentSummary(documents);if(module==="Reportes"){const s=summary;return <PortalShell title="Reportes" description="Indicadores construidos únicamente con documentación disponible.">{loading?<Empty title="Cargando indicadores" body=""/>:documents.length===0?<Empty title="Aún no hay datos para reportar" body="Los indicadores aparecerán cuando existan documentos procesados."/>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Documentos",s.received],["Procesando",s.processing],["Revisión",s.attention],["Aprobados",s.approved]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-3xl font-extrabold">{v}</p><p className="mt-1 text-sm font-semibold text-slate-600">{l}</p></div>)}</div>}</PortalShell>}
const content=module==="Aclaraciones"?["No hay aclaraciones registradas","Este módulo se habilitará cuando existan registros persistidos vinculados a documentos."]:["Perfil preparado para configuración","Los datos empresariales solo se mostrarán o editarán cuando cuenten con persistencia y permisos correspondientes."];return <PortalShell title={module} description="Información operativa disponible."><Empty title={content[0]} body={content[1]}/></PortalShell>}
export function DetailPage({id}:{id:string}){const {documents,loading}=usePortalDocuments();const doc=documents.find(d=>d.id===id);return <PortalShell title="Detalle del documento" description="Datos disponibles del documento seleccionado.">{loading?<Empty title="Cargando documento" body=""/>:!doc?<Empty title="Documento no disponible" body="No fue encontrado en la información actualmente accesible."/>:<div className="grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-4 lg:col-span-1">{doc.signed_url?(doc.nombre_archivo?.toLowerCase().endsWith(".pdf")?<iframe title="Archivo original" src={doc.signed_url} className="h-96 w-full rounded-lg border"/>:<a href={doc.signed_url} target="_blank" className="flex h-56 items-center justify-center rounded-lg bg-slate-100 text-sm font-bold text-[#ff6a00]">Abrir archivo original</a>):<Empty title="Sin archivo disponible" body="Este registro no tiene un archivo asociado."/>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 lg:col-span-2"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">{doc.nombre_archivo||doc.tipo_documento}</h2><p className="mt-1 text-sm text-slate-500">{doc.tipo_documento}</p></div><Badge status={doc.estatus}/></div><dl className="mt-6 grid gap-4 sm:grid-cols-2">{[["RFC detectado",doc.rfc_detectado],["Fecha",doc.fecha_documento],["Total",doc.total==null?null:`$${Number(doc.total).toLocaleString("es-MX")}`],["Confianza",doc.confidence==null?null:`${doc.confidence}%`]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value||"No disponible"}</dd></div>)}</dl><div className="mt-6 rounded-xl border border-slate-200 p-4"><h3 className="font-bold">Notas del contador</h3><p className="mt-2 text-sm text-slate-600">{doc.notas_contador||"No hay notas registradas."}</p></div></section></div>}</PortalShell>}
