"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, FileText, FolderOpen, Search, UploadCloud } from "lucide-react";
import { PortalShell } from "./portal-shell";
import { DocumentUploader } from "./document-uploader";
import { PortalDocument, useDocumentSummary, usePortalDocuments } from "./portal-data";
import { useWorkspace } from "./workspace-context";
import { DocumentActions, DocumentActivityTimeline } from "./document-actions";
import { normalizeDocumentStatus, statusMeta } from "@/lib/document-status";

function Empty({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><FolderOpen className="mx-auto text-slate-400"/><h2 className="mt-3 font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{body}</p></div>; }
function Badge({ status }: { status: string }) { const meta = statusMeta[normalizeDocumentStatus(status)]; return <span className={`rounded-full px-2 py-1 text-xs font-bold ${meta.className}`}>{meta.label}</span>; }
function List({ documents }: { documents: PortalDocument[] }) { const { href } = useWorkspace(); return documents.length ? <div className="overflow-hidden rounded-2xl border bg-white">{documents.map((document) => <Link href={href(`/expediente/${document.id}`)} key={document.id} className="grid gap-2 border-b p-4 hover:bg-orange-50 md:grid-cols-[2fr_1fr_1fr]"><span><b>{document.nombre_archivo || document.tipo_documento}</b><small className="block text-slate-500">{document.tipo_documento}</small></span><span>{document.total == null ? "Sin importe" : `$${Number(document.total).toLocaleString("es-MX")}`}</span><Badge status={document.estatus}/></Link>)}</div> : <Empty title="Sin documentos" body="No existen documentos para este contexto."/>; }
export function HomePage() { const { documents, loading, error } = usePortalDocuments(); const { href } = useWorkspace(); const s = useDocumentSummary(documents); return <PortalShell title="Inicio" description="Resumen del período autorizado."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Documentos",s.received],["Procesando",s.processing],["Revisión",s.attention],["Aprobados",s.approved]].map(([label,value])=><Link key={String(label)} href={href("/expediente")} className="rounded-2xl border bg-white p-5"><FileText className="text-[#ff6a00]"/><p className="mt-3 text-3xl font-bold">{loading?"—":value}</p><p className="text-sm text-slate-600">{label}</p></Link>)}</div>{error?<p className="mt-5 text-red-700">{error}</p>:<div className="mt-6"><List documents={documents.slice(0,5)}/><Link href={href("/enviar-documentos")} className="mt-4 inline-flex rounded-xl bg-[#ff6a00] px-4 py-3 font-bold text-white"><UploadCloud className="mr-2"/>Enviar documentos</Link></div>}</PortalShell>; }
export function UploadPage() { const { refresh }=usePortalDocuments(); return <PortalShell title="Enviar documentos" description="Carga privada en el período seleccionado."><DocumentUploader onComplete={refresh}/></PortalShell>; }
export function ExpedientePage() { const { workspace, href }=useWorkspace(); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [page,setPage]=useState(1); const [data,setData]=useState<any>({loading:true,documents:[]}); const load=useCallback(async()=>{if(!workspace?.company||!workspace.period){setData({loading:false,documents:[],error:"CONTEXT_REQUIRED"});return;}setData((x:any)=>({...x,loading:true}));try{const res=await fetch(href("/api/app-data",{page:String(page),page_size:"20",search:search||null,status:status||null}),{cache:"no-store"});const value=await res.json();if(!res.ok)throw new Error(value.code);setData({loading:false,documents:value.documents||[],pagination:value.pagination});}catch(e){setData({loading:false,documents:[],error:e instanceof Error?e.message:"ERROR"});}},[href,page,search,status,workspace?.company,workspace?.period]);useEffect(()=>{void load()},[load]);return <PortalShell title="Expediente" description="Documentos autorizados."><div className="mb-4 grid gap-3 sm:grid-cols-2"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={16}/><input className="bro-input !mt-0 pl-9" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar por archivo o RFC"/></label><select className="bro-input !mt-0" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Todos los estados</option><option value="needs_review">Requiere revisión</option><option value="reviewed">Revisado</option><option value="approved">Aprobado</option></select></div>{data.loading?<Empty title="Cargando expediente" body=""/>:data.error?<Empty title="No fue posible cargar" body={data.error}/>:<><List documents={data.documents}/><div className="mt-4 flex justify-between"><button disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><span>{page}/{Math.max(1,Math.ceil((data.pagination?.total||0)/20))}</span><button disabled={page>=Math.ceil((data.pagination?.total||0)/20)} onClick={()=>setPage(page+1)}>Siguiente</button></div></>}</PortalShell>; }
export function EmptyModule({ module }: { module: "Aclaraciones"|"Reportes"|"Perfil y configuración" }) { return <PortalShell title={module} description="Información autorizada."><Empty title="Sin datos disponibles" body="Este módulo mostrará información cuando existan registros persistidos."/></PortalShell>; }
export function DetailPage({ id }: { id: string }) { const { workspace, href }=useWorkspace(); const [state,setState]=useState<any>({loading:true}); const load=useCallback(async()=>{if(!workspace?.company||!workspace.period)return setState({loading:false,error:"CONTEXT_REQUIRED"});try{const r=await fetch(href(`/api/documents/${id}`),{cache:"no-store"});const v=await r.json();if(!r.ok)throw new Error(v.code);setState({loading:false,document:v.document});}catch(e){setState({loading:false,error:e instanceof Error?e.message:"ERROR"});}},[href,id,workspace?.company,workspace?.period]);useEffect(()=>{void load()},[load]);const d=state.document;return <PortalShell title="Detalle del documento" description="Información y acciones autorizadas."><Link href={href("/expediente")} className="mb-4 inline-flex items-center text-[#c95000]"><ArrowLeft size={16}/>Volver al expediente</Link>{state.loading?<Empty title="Cargando documento" body=""/>:!d?<Empty title="Documento no disponible" body={state.error||"No encontrado."}/>:<div className="grid gap-5 lg:grid-cols-3"><aside className="rounded-2xl border bg-white p-4">{d.signed_url?<a className="block rounded-xl bg-slate-100 p-6 text-center font-bold text-[#c95000]" href={d.signed_url} target="_blank" rel="noreferrer">Abrir o descargar original</a>:<Empty title="Sin vista previa" body="No hay archivo disponible."/>}</aside><section className="rounded-2xl border bg-white p-5 lg:col-span-2"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{d.nombre_archivo}</h2><p className="text-sm text-slate-500">{d.tipo_documento}{d.categoria?` · ${d.categoria}`:""}</p></div><Badge status={d.estatus}/></div><dl className="mt-5 grid gap-3 sm:grid-cols-2">{[["RFC",d.rfc_detectado],["Fecha",d.fecha_documento],["Total",d.total==null?null:`$${Number(d.total).toLocaleString("es-MX")}`],["Carga",new Date(d.created_at).toLocaleString("es-MX")]].map(([k,v])=><div key={String(k)} className="rounded-lg bg-slate-50 p-3"><dt className="text-xs text-slate-500">{k}</dt><dd>{v||"No disponible"}</dd></div>)}</dl><DocumentActions id={d.id} status={d.estatus} onChanged={load}/><DocumentActivityTimeline events={d.activity||[]}/></section></div>}</PortalShell>; }
