"use client";

import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { FileUp, ImagePlus, RotateCcw, X } from "lucide-react";

const allowed = ["application/pdf","application/xml","text/xml","image/jpeg","image/png","image/webp"];
const max = 20 * 1024 * 1024;
export function DocumentUploader({onComplete}:{onComplete:()=>Promise<void>}) {
  const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const invalid = useMemo(()=>files.find(f=>!allowed.includes(f.type)||f.size===0||f.size>max),[files]);
  const select=(event:ChangeEvent<HTMLInputElement>)=>{ const incoming=Array.from(event.target.files||[]); const unique=incoming.filter((file,index,list)=>list.findIndex(x=>x.name===file.name&&x.size===file.size)===index).slice(0,10); setFiles(unique); setError(""); setMessage(""); };
  const submit=async(event:FormEvent<HTMLFormElement>)=>{ event.preventDefault(); if(!files.length||invalid)return; setBusy(true);setError("");setMessage(""); const form=event.currentTarget; try { for(const file of files){ const fd=new FormData(form);fd.set("clientName",String(fd.get("legalName")||""));fd.set("documentType",String(fd.get("documentType")||""));fd.set("fiscalPeriod",String(fd.get("fiscalPeriod")||""));fd.set("file",file);const res=await fetch("/api/process-document",{method:"POST",body:fd});const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.error||"No fue posible procesar el archivo.");} setMessage(`${files.length} documento(s) recibido(s) correctamente.`);setFiles([]);form.reset();await onComplete(); }catch(err){setError(err instanceof Error?err.message:"Error técnico al enviar los documentos.");}finally{setBusy(false);} };
  return <form onSubmit={submit} className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:grid-cols-3"><div className="space-y-4 lg:col-span-2"><label className="block text-sm font-bold">Razón social<input required name="legalName" placeholder="Razón social registrada" className="bro-input"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-bold">RFC<input required name="rfc" placeholder="RFC" className="bro-input"/></label><label className="block text-sm font-bold">Periodo fiscal<input required name="fiscalPeriod" placeholder="Ej. 2026-08" className="bro-input"/></label></div><label className="block text-sm font-bold">Tipo documental<select name="documentType" className="bro-input"><option>Factura recibida</option><option>Factura emitida</option><option>Estado de cuenta</option><option>Comprobante de pago</option><option>Constancia fiscal</option><option>Otro</option></select></label><label className="block text-sm font-bold">Nota opcional<textarea name="notes" className="bro-input min-h-24" placeholder="Contexto para el despacho"/></label></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm font-bold">Archivos</p><p className="mt-1 text-xs text-slate-500">PDF, XML, JPG, PNG o WebP · máximo 20 MB por archivo · hasta 10 archivos.</p><label className="mt-4 flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-white p-4 text-center hover:border-[#ff6a00]"><FileUp className="text-[#ff6a00]"/><span className="mt-2 text-sm font-bold">Seleccionar documentos</span><span className="mt-1 text-xs text-slate-500">En móvil puedes tomar una fotografía.</span><input className="sr-only" type="file" multiple accept="application/pdf,application/xml,text/xml,image/jpeg,image/png,image/webp" capture="environment" onChange={select}/></label>{files.length>0&&<div className="mt-3 space-y-2">{files.map(file=><div key={`${file.name}-${file.size}`} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white p-2 text-xs"><ImagePlus size={14}/><span className="min-w-0 flex-1 truncate">{file.name}</span><button type="button" aria-label={`Quitar ${file.name}`} onClick={()=>setFiles(files.filter(x=>x!==file))}><X size={14}/></button></div>)}</div>}{invalid&&<p className="mt-3 text-xs font-semibold text-red-700">Hay un archivo vacío, no permitido o mayor a 20 MB.</p>}<button disabled={busy||!files.length||!!invalid} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#ff6a00] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?<><RotateCcw size={16}/> Enviando…</>:"Confirmar envío"}</button>{message&&<p className="mt-3 text-sm font-semibold text-emerald-700">{message}</p>}{error&&<p className="mt-3 text-sm font-semibold text-red-700">{error}</p>}</div></form>;
}
